# Generated by Django 5.2.3 on 2025-06-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_basket_unique_together_order_status_and_more'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Color',
            new_name='ProductColor',
        ),
    ]
